title: Content Design Starter Template
description: Practical templates, workflows, and guidelines for creating clear, accessible, user-focused content.
theme: minima
author:
  name: Jen Kelleman
show_excerpts: true
baseurl: "/content-design-starter-template"
url: "https://jkelleman.github.io"

minima:
  skin: auto
  social_links:
    github: https://github.com/jkelleman/content-design-starter-template